### ISSUE TITLE
Lots of slack errors in error log

### ISSUE THREAD

**Issue by regulartim** [intelowlproject/GreedyBear#415]
When Slack is not configured, GreedyBear once per hour writes an error to the error log, making it harder to find important errors. 

```
2024-12-20 15:33:00,267 - greedybear.slack - send_message - ERROR - The request to the Slack API failed. (url: https://slack.com/api/chat.postMessage)
The server responded with: {'ok': False, 'error': 'not_authed'}
Traceback (most recent call last):
  File "/opt/deploy/greedybear/greedybear/slack.py", line 17, in send_message
    sc.chat_postMessage(channel=channel, text=text, mrkdwn=True)
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/client.py", line 2710, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 157, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 188, in _sync_send
    return self._urllib_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 319, in _urllib_api_call
    ).validate()
      ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://slack.com/api/chat.postMessage)
The server responded with: {'ok': False, 'error': 'not_authed'}
```

**Comment by mlodic** [comment]
I just pushed a little fix in `develop`, thanks for reporting
